Remove exif info from image uploads
kitsune-soc/kitsune pull request #352
Opened 2023-09-21 16:51 UTC by Zeerooth

Resolves https://github.com/kitsune-soc/kitsune/issues/263

Supports jpeg, png and webp (just like [img-parts](https://docs.rs/img-parts/latest/img_parts/index.html))

Some things to still consider:
- Unfortunately, to parse the image and manipulate it we have to load it whole into the memory, but I don't think there's any way around that, especially when looking at currently available libraries.
- Should we lock this behaviour behind a feature/config option? I personally think it's best not to make it opt-out.
- We don't know what the file size is going to be in the multipart upload, so I use `BytesMut` without any capacity, which means it has to reallocate when receiving new stream chunks. This is unfortunate but again, I don't think there's a way around that aspect too.

2023-09-21 17:42 UTC, aumetra requested changes
just some small nits

2023-09-21 17:43 UTC, aumetra commented
this looks fine, I would keep it as something that is just forced on the users. I don't like the idea that an instance could accidentally let users post their geolocation.

And yeah, it's not possible to do without buffering with current crates unfortunately. I wanna check for better alternatives but until then I would just add this

2023-09-21 17:53 UTC, Zeerooth commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
Yeah I did that originally, but mime crate doesn't have the WebP type in it, so it would be an awkward mix

2023-09-21 18:00 UTC, aumetra commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
You can do the following: `static IMAGE_WEBP: Lazy<Mime> = Lazy::new(|| Mime::from_str("image/webp").unwrap());`

These few milli-/microseconds for the first evaluation are negligable

2023-09-21 18:08 UTC, aumetra commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
Hah, interesting https://github.com/hyperium/mime/pull/129

2023-09-21 18:26 UTC, Zeerooth commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
> You can do the following: `static IMAGE_WEBP: Lazy<Mime> = Lazy::new(|| Mime::from_str("image/webp").unwrap());`
> 
> These few milli-/microseconds for the first evaluation are negligable

Interesting, the compiler won't let me match against such a type

```rust
static IMAGE_WEBP: Lazy<mime::Mime> = Lazy::new(|| "image/webp".parse().unwrap());
```

```
error[E0532]: expected unit struct, unit variant or constant, found static `self::IMAGE_WEBP`
  --> crates/kitsune-core/src/service/attachment.rs:44:46
   |
44 |         mime::IMAGE_JPEG | mime::IMAGE_PNG | self::IMAGE_WEBP => true,
   |                                              ^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant
```

2023-09-21 18:27 UTC, Zeerooth commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
> Hah, interesting [hyperium/mime#129](https://github.com/hyperium/mime/pull/129)

Yeah.. I've seen that before, apparently that crate isn't really maintained much

2023-09-22 13:03 UTC, tesaguri commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
> Interesting, the compiler won't let me match against such a type

The error might be easier to understand if you think of the fact that the code is equivalent to:

```rust
matches!(mine, .. | Lazy { cell: OnceCell::new(), init: Cell::new(Some(|| Mime::from_str("image/webp").unwrap())) }
```

… which won't make much sense intuitively. If you are curious, the pattern match is not just applying `PartialEq` to the matched expression, but it instead checks for something called [structural equality](https://doc.rust-lang.org/1.71.1/core/marker/trait.StructuralPartialEq.html.).

Well, in short, I agree that you cannot do that.

2023-09-22 13:50 UTC, aumetra commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
> but it instead checks for something called [structural equality](https://doc.rust-lang.org/1.71.1/core/marker/trait.StructuralPartialEq.html.).

Oh yeah, right, sorry about sending that silly suggestion. I was writing that yesterday while on a walk lol.

I decided to try forking the `mime` crate and adding some things in an API compatible way so we can just patch it in

2023-09-23 12:29 UTC, Zeerooth commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
@aumetra so I guess this PR is blocked until we can make the changes to the forked `mime` crate

if you get around to doing this and need some help implementing stuff then let us know please :)

2023-09-23 12:50 UTC, aumetra commented on crates/kitsune-core/src/service/attachment.rs
> +    matches!(mime, "image/jpeg" | "image/png" | "image/webp")
Oh, no no. Don't worry. We can just move forward with this PR. Just maybe add a comment above the line for now

2023-09-23 13:37 UTC, aumetra approved these changes
Looks good now, thanks!

2023-09-23 13:54 UTC, merged